name: Wails build

on:
  push:
    tags:
      - "*"

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: "App"
            platform: "linux/amd64"
            os: "ubuntu-latest"
            goos: "linux"
            goarch: "amd64"
          - name: "App"
            platform: "windows/amd64"
            os: "windows-latest"
            goos: "windows"
            goarch: "amd64"
          - name: "App"
            platform: "darwin/universal"
            os: "macos-latest"
            goos: "darwin"
            goarch: "amd64" # Universal build handles ARM64 too

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Linux Dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm" # Enables caching for pnpm dependencies
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build wails App
        env:
          GOOS: ${{ matrix.build.goos }}
          GOARCH: ${{ matrix.build.goarch }}
        run: |
          wails build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.name }}-${{ matrix.build.platform }}
          path: build/bin/* # Artifacts are found here after a wails build
